app = "qa-backend-faiss"
primary_region = "nrt"

[build]

[env]
  PORT = "8080"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

# 헬스체크는 배포 후 정상 작동 확인 시 다시 활성화하는 것을 권장합니다.
# [[http_service.checks]]
#   interval = "30s"
#   grace_period = "30s"
#   method = "get"
#   path = "/health"
#   protocol = "http"
#   timeout = "15s"

[machine]
  # 메모리 설정: 무료 계정은 256MB 또는 512MB가 일반적입니다.
  # 서비스가 불안정하면 512MB로 늘려보세요.
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1 # CPU 코어 수도 줄여서 리소스 사용을 최소화합니다.

[[mounts]]
  source = "qa_data"
  destination = "/app/data"